version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html

# hooks:
#   BeforeInstall:
#     - location: scripts/before_install.bash
#       timeout: 300
#       runas: root
#   AfterInstall:
#     - location: scripts/after_install.bash
#       timeout: 300
#       runas: root