version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/laravel_practice

hooks:
  BeforeInstall:
    - location: ./laravel/scripts/before_install.bash
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: ./laravel/scripts/after_install.bash
      timeout: 600
      runas: ubuntu